name: Deploy to local server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: git pull origin main

      - name: Restart API service
        run: |
          C:\nssm\win64\nssm.exe stop DamageAPI
          C:\nssm\win64\nssm.exe start DamageAPI

      - name: Build React app
        run: |
          cd C:\Users\dewet\OneDrive\Documents\repos\Damage\damageui
          npm install
          npm run build

      - name: Restart UI service
        run: C:\nssm\win64\nssm.exe restart DamageUI